# Generated by Django 5.2.5 on 2025-08-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='books_read',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_genres',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='quiz_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('genres', models.ManyToManyField(blank=True, to='users.genre')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='books_read',
            field=models.ManyToManyField(blank=True, to='users.book'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, to='users.genre'),
        ),
    ]
