# Generated by Django 5.2.5 on 2025-09-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_genre_remove_customuser_books_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
