# Generated by Django 5.2.5 on 2025-10-16 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='primary_match',
        ),
        migrations.RemoveField(
            model_name='match',
            name='secondary_match',
        ),
        migrations.AddField(
            model_name='match',
            name='match_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
