# Generated by Django 5.2.5 on 2026-03-31 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='previous_matches',
            field=models.ManyToManyField(blank=True, related_name='matched_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
